// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/qrcode": {
            "get": {
                "description": "Get QR code as PNG image for WhatsApp login",
                "produces": [
                    "image/png"
                ],
                "tags": [
                    "authentication"
                ],
                "summary": "Get QR Code",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "ID do setor para gerar o QR code",
                        "name": "sector_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "QR code em formato PNG",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Erro de requisição inválida",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "QR code não encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/qrcode-base64": {
            "get": {
                "description": "Get QR code as base64 string for WhatsApp login",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication"
                ],
                "summary": "Get QR Code Base64",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "ID do setor para gerar o QR code",
                        "name": "sector_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "QR code em base64 e status",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Erro de requisição inválida",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "QR code não encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/send-audio": {
            "post": {
                "description": "Send an audio file to a WhatsApp contact",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Send an audio file",
                "parameters": [
                    {
                        "description": "Audio message details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AudioMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/send-document": {
            "post": {
                "description": "Send a document file to a WhatsApp contact",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Send a document",
                "parameters": [
                    {
                        "description": "Document message details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DocumentMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/send-image": {
            "post": {
                "description": "Send an image with optional caption to a WhatsApp contact",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Send an image",
                "parameters": [
                    {
                        "description": "Image message details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ImageMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/send-message": {
            "post": {
                "description": "Send a text message to a WhatsApp contact",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Send a text message",
                "parameters": [
                    {
                        "description": "Message details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/send-typing": {
            "post": {
                "description": "Send a typing indication to a WhatsApp contact with specified duration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Send typing indication",
                "parameters": [
                    {
                        "description": "Typing indication details with duration in seconds",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TypingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "Check if WhatsApp is connected",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication"
                ],
                "summary": "Check Connection Status",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "ID do setor para verificar o status",
                        "name": "sector_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Status da conexão",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Erro de requisição inválida",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AudioMessageRequest": {
            "type": "object",
            "properties": {
                "audio_path": {
                    "type": "string",
                    "example": "/path/to/audio.mp3"
                },
                "recipient": {
                    "type": "string",
                    "example": "5511999999999"
                },
                "sector_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.DocumentMessageRequest": {
            "type": "object",
            "properties": {
                "file_path": {
                    "type": "string",
                    "example": "/path/to/document.pdf"
                },
                "recipient": {
                    "type": "string",
                    "example": "5511999999999"
                },
                "sector_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.ImageMessageRequest": {
            "type": "object",
            "properties": {
                "caption": {
                    "type": "string",
                    "example": "Legenda da imagem"
                },
                "image_path": {
                    "type": "string",
                    "example": "/path/to/image.jpg"
                },
                "recipient": {
                    "type": "string",
                    "example": "5511999999999"
                },
                "sector_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.MessageRequest": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Olá, como vai?"
                },
                "recipient": {
                    "type": "string",
                    "example": "5511999999999"
                },
                "sector_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.TypingRequest": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "integer",
                    "default": 5,
                    "example": 5
                },
                "recipient": {
                    "type": "string",
                    "example": "5511999999999"
                },
                "sector_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "WhatsApp Bot API",
	Description:      "A WhatsApp bot API that supports sending messages, images, audio, and documents",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
